Path = "../config.toml"
ErrLog = "./errlog.txt"

[FileWatcher]
  Dir = "../inbound/"

[WebService]
  Port = 1323
  Version = "0.1.0"  

[Group]
  APP = "/app"
  API = "/api"

[Route]
  Greeting = "/v#/greeting"
  ID = "/v#/id"
  Pub = "/v#/pub"  
  GQL = "/v#/gql"
  GQL2 = "/v#/gql2"
  Del = "/v#/del"
  Obj = "/v#/obj"
  Scm = "/v#/scm"
  GQLTxt = "/v#/qrytxt"
  Upload = "/v#/upload"

[RPC]
  Namespace = "GdYh1auVHBsLGsoNHu1z7JWzs6cy3kmS1s4ZZssekBmd"
  Server = "192.168.245.135"
  Port = 5777
  CtxList = ["demo", "demo1", "demo2"]
  CtxPrivDef = "privctrl"
  CtxPrivID = "ctxid"

[Query]
  SchemaDir = "../gql/qSchema/"
  SampleTxtDir = "../gql/qTxt/"
  ParamPathDir = "../rest/parampath/"

[Debug]
  TrialPub = false
  TrialQry = false
